name: university_workshop

profile: university_workshop

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_dataset_name>_raw'
  university_workshop:
    + dataset: raw

models:
  university_workshop:
    +static_analysis: strict
